config/routes.rb
Rails.application.routes.draw do
  resources :user_venues
  resources :user_artists
  get '/remove_users', to: 'user_artists#remove'
  get '/remove_venues', to: 'user_venues#remove'
  resources :users
  resources :artist_genres
  resources :artist_likes
  resources :genres
  resources :bookings
  resources :posts
  # get '/posts/new/:artist_id', to: 'posts#new', as: 'posts/new'
  # post '/posts/new/:artist_id', to: 'posts#create'
  resources :venues
  resources :artists
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/home', to: 'static#home'
  post '/venues/endorse', to: 'venues#endorse'
  post '/venues/unendorse', to: 'venues#unendorse'
  get '/search', to: 'artists#search'

  post '/artists/like', to: 'artists#like'
  get '/artists/like', to: 'artists#like'
  post '/artists/like_tile', to: 'artists#like_tile'
  post '/artists/unlike', to: 'artists#unlike'

  # get '/artists/posts', to: 'artists#posts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :bookings
    has_many :artist_genres
    has_many :genres, through: :artist_genres
    accepts_nested_attributes_for :genres
    has_many :posts
    has_many :venues, through: :bookings
    has_many :artist_likes
    has_many :venues, through: :artist_likes
    has_one_attached :avatar
    validates :name, presence: true
    has_many :user_artists
    has_many :users, through: :user_artists
    has_many :user_likes_artists
    # has_many :users, through: :user_likes_artists #remains to be seen if this messes with other artist.users
    
    def artist_avatar
        if self.avatar.attached?
            image_tag artist.avatar
        else
            image_tag 'default_avatar.jpg'
        end
    end

    def likers    
        self.user_likes_artists.map {|l| l.user}
    end    
   

end

app/controllers/artists_controller.rb
class ArtistsController < ApplicationController
    before_action :find_artist, only: [:show, :edit, :update, :destroy]

    def index
        @artists = Artist.all
        @booking = Booking.new
    end

    def search
        @artists = []
        @booking = Booking.new
        if search_params[:g] != ""
            genre = Genre.find_by(name: search_params[:g])
            @artists = genre.artists
            if @artists == []
                @artists = Artist.all
                @message = "There are no artists by that genre."
            end
        end
        if search_params[:q] != ""
            artist = Artist.find_by(name: search_params[:q])
            if !artist.nil? 
            # if !@artists.include?(artist)
                @artists << artist
            # end
            end
            @artists.uniq
        end
        if @artists.nil? || @artists.empty?
            @artists = Artist.all
            @message = "No artists by that search."
        end
        render :index
    end

    def show 
        @bookings = @artist.bookings
        @post = Post.new
        # @venues = @artist.venues #@artist.venues refers to endorsements 
        @venues = @bookings.map {|b| b.venue }
        @posts = @artist.posts
    end

    def new
        require_login
        @artist = Artist.new
        @artist.genres.build()
    end

    def like
        @artist = Artist.find(like_params[:artist_id])
        if like = UserLikesArtist.find_by(user_id: current_user.id, artist_id: @artist.id)
            like.destroy
        else
            UserLikesArtist.create(user_id: current_user.id, artist_id: @artist.id) 
        end
        if like_params[:locus] == "artists"
            redirect_to artists_path
        else
            redirect_to artist_path(@artist)
        end
    end

    # def like_tile
    #     @artist = Artist.find(like_params[:artist_id])
    #     UserLikesArtist.create(user_id: current_user.id, artist_id: @artist.id)
    #     redirect_to artists_path
    # end

    def create
        @artist = Artist.new(artist_params)
        if @artist.save
            @artist.save
            UserArtist.create(user: current_user, artist: @artist)
            redirect_to artist_path(@artist)
        else
            render :new
        end
    end

    def edit
        require_login
    end

    def update
        if @artist.update(artist_params)
            @artist.save
            redirect_to artist_path(@artist)
        else
            render :edit
        end
    end

    def destroy
        artist = Artist.find_by(id: params[:id])
        artist.destroy
        if user
            redirect_to user_path(user) 
        else
            redirect_to artists_path
        end
    end

    def posts
    end

    private

    def find_artist
        @artist = Artist.find(params[:id])
    end

    def artist_params
        params.require(:artist).permit(:name, :description, :image_url, :avatar, genre_ids: [], genres_attributes: [:name])
    end

    def  like_params
        params.permit(:artist_id, :locus)
    end    

    def require_login
        unless session.include? :user_id
        redirect_to login_path
        end
    end

    def search_params
        params.permit(:q, :g)
    end
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/views/artists/_list_tiles.html.erb
<% if @artists %>        
    <%@artists.each do |artist|%>
        <div class="tile <%= artist.users.include?(current_user) ? 'mine' : '' %> ">
            <div>
                <a href="<%=artist_path(artist)%>">
                    <%if artist.image_url%>
                        <%= image_tag artist.image_url, class: "headshot" %>
                    <%elsif artist.avatar.attached?%>
                        <%=image_tag artist.avatar, class: "headshot" %>
                    <%else %>
                        <%=image_tag "https://upload.wikimedia.org/wikipedia/commons/1/1e/Default-avatar.jpg", class: "headshot"%>
                    <%end%>
                </a>
                <% if current_user %>
                    <%= form_tag  artists_like_path do %>
                        <%= hidden_field_tag 'artist_id', artist.id%>
                        <%= hidden_field_tag 'locus', 'artists'%>
                        <input type="submit" value="♥" class="like_button <%= artist.likers.include?(current_user) ? 'active' : ''%>">
                    <% end %>
                <% end %>
            </div>
                <p class='artist-name'><%= link_to artist.name, artist_path(artist) %>
                </p>
                <p>♥ <%= pluralize(artist.user_likes_artists.count, "Likes") %></p>
                <p>★ <%= pluralize(artist.artist_likes.count, " Endorsement") %></p>
            <% artist.genres.each do |g| %>
                <%= link_to g.name, genre_path(g), class: 'genre-links' %> 
            <% end %>
            <div class="tile-options">
            <!-- begin booking -->
                <% if current_user && (current_user.venues.count > 0) %>   
                    <%= form_for(@booking, url: {controller: 'bookings', action: 'create'}, method: :post) do |f| %>
                            <% if !@venue %>
                                <%= f.hidden_field :venue_name, :value => current_user.venues.last.name%>
                            <% else %> 
                                <%= f.hidden_field :venue_name, :value => @venue.name%>
                            <% end %>   
                            <%= f.hidden_field :artist_name, :value => artist.name%>
                            <%= f.submit "Book" %>     
                        <% end %>
                <% end %>
                <!-- end booking -->
                <% if current_user && @venue && current_user.venues.include?(@venue) %> 
                    <% if  @venue.artist_likes.select {|l| l.artist == artist}.count >= 1 %>
                        <%= form_for(@venue, url: {controller: 'venues', action: 'unendorse'}, method: :post) do |f| %>
                            <%= f.hidden_field :venue_id, :value => @venue.id%>
                            <%= f.hidden_field :artist_name, :value => artist.name%>
                            <%= f.submit "Un-Endorse" %>     
                        <% end %>
                    <% else %>
                        <%= form_for(@venue, url: {controller: 'venues', action: 'endorse'}, method: :post) do |f| %>
                            <%= f.hidden_field :venue_id, :value => @venue.id%>
                            <%= f.hidden_field :artist_name, :value => artist.name%>
                            <%= f.submit "Endorse" %>     
                        <% end %>
                    <% end %>    
                <% end %>
            </div>
        </div>
    <%end%>
<% end %>

app/views/artists/edit.html.erb
<h1 class="title">Edit Artist</h1>

<%if @artist.errors.any?%>
<ul class="errors">
    <%@artist.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>
    <%end%>
</ul>
<%end%>

<%=form_for @artist do |f|%>
    <%=f.label :name%>
    <%=f.text_field :name%><br>

    <%=f.file_field :avatar%>
    <%=f.label :description%>
    <%=f.text_field :description%><br>
    <%=f.label "Genre tags"%>
    <%=f.collection_check_boxes :genre_ids, Genre.all, :id, :name%><br>
    <%=f.fields_for :genres, @artist.genres.build do |g|%>
    <%=g.text_field :name%><br>
<%end%>
<%=f.submit "Confirm Changes"%>
<%end%>

app/views/artists/index.html.erb
<h1 class="title">Artists</h1>

<div class="search">
<%=form_tag "/search", method: "get" do %>
    <%=label_tag(:q, "Artist Name:")%>
    <%=text_field_tag(:q)%>
    <%=label_tag(:g, "Filter by Genre:")%>
    <input type="text" name="g" list="genres">
    <datalist id='genres'>
    <%Genre.all.each do |genre|%>
        <option value="<%=genre.name%>">
    <%end%>
    </datalist></input>
    <%=submit_tag("Search")%>
    <%end%>
</div>

<%if @message%>
    <p><%=@message%></p>
<%end%>

<%= render 'list_tiles' %>

app/views/artists/new.html.erb
<h1 class="title">New Artist Form</h1>

<%if @artist.errors.any?%>
<ul class="errors">
    <%@artist.errors.full_messages.each do |msg| %>
        <li><%=msg%></li>
    <%end%>
</ul>
<%end%>

<%=form_for @artist do |f|%>
    <%=f.label :name%>
    <%=f.text_field :name%><br>
    <%=f.file_field :avatar%>
    <%=f.label :description%>
    <%=f.text_field :description%><br>
    <%=f.label "Genre tags"%>
    <%=f.collection_check_boxes :genre_ids, Genre.all, :id, :name%><br>
    <%=f.fields_for :genres, @artist.genres.build do |g|%>
        <%=g.text_field :name%><br>
    <%end%>
    <%=f.submit "Create Artist"%>
<%end%>

app/views/artists/show.html.erb
<h1 class="title"><%=@artist.name%></h1>

<!--Headshot -->
<div class="headshot">
    <% if @artist.image_url%>
        <%=image_tag @artist.image_url, class: "headshot"%>
    <% elsif @artist.avatar.attached?%>
        <%=image_tag @artist.avatar, class: "headshot"%>
    <%else%>
        <%=image_tag "https://upload.wikimedia.org/wikipedia/commons/1/1e/Default-avatar.jpg", class: "headshot"%>
    <%end%>


    <div class="profile_buttons">
        <!--buttons to like; any user can-->
    <% if current_user %>
            <%= form_tag  artists_like_path do %>
                <%= hidden_field_tag 'artist_id', @artist.id%>
                <input type="submit" value="♥" class="<%= @artist.likers.include?(current_user) ? 'like_button' : ''%>">  
            <% end %>
        <% end %> 
    </div>
</div>


<!--likes-->

<div class="likes"><%= pluralize(@artist.user_likes_artists.count, "Like") %></div>
<!--< % if @artist.user_likes_artists %>
    < % = @artist.user_likes_artists.map { |l| l.user.username}.join(', ')  %>
< % end %>-->

<!--description -->

<p><%=@artist.description%></p>

<div class="post_form">
    <%if current_user && current_user.artists.include?(@artist)%>
        <h5>What's on your mind?</h5>
        <%=form_for @post do |f| %>
            <%=f.hidden_field :artist_id, value: @artist.id%>
            <%=f.text_area  :content%><br>
            <%=f.file_field :media%><br>
            <%=f.submit "Create Post"%>
        <%end%>
    <%end%>
</div>

<!--genres-->

<% if @artist.genres.count > 0 %>
    <h2>Genres:</h2>
    <p>
        <%@artist.genres.each do |genre|%>
            <%=link_to genre.name, genre_path(genre) %>
        <%end%>
    </p>
<%end%>


<!--there are two different posts partials; this one (./posts/posts) is for more full posts, but ./posts/posts_tiles is for a short preview -->
<% if @posts.count > 0 %>
    <h2>Posts:</h2>
    <%= render '/posts/posts' %>
<%elsif %>
    <p class="note">This artist has not made any posts yet.</p>
<% end %>


<!--bookings as text blocks (not calendar) -->
<% if @artist.bookings.count > 0 %>
    <div class = "artist-bookings">
        <h2>Upcoming Events:</h2>
        <%= render './bookings/list_tiles' %>
    </div>
<%end%>


<!-- endorsements -->
<% if @artist.artist_likes.count %>
    <h2>Endorsements:</h2>
    <%= pluralize(@artist.artist_likes.count, "Endorsement") %><br>
    <% @artist.artist_likes.each do |l|  %>
        <div class="tile" >
            <% if l.venue.image_url %>
                <%= image_tag l.venue.image_url, class: "icon" %><br>
            <% end %>
            <%= link_to l.venue.name, l.venue %>
        </div>
    <% end %>
<% end %>



<!-- calendar -->
<% if @bookings.count > 0%>
    <h2> Shows with this Artist: </h2>
    <%= render './bookings/calendar' %>
<% elsif %>
    <p class="note">This artist has not booked any shows yet.</p>
<%end%>


<!-- venues -->
<% if @venues.count > 0 %> 
    <h2> Places this Artist has booked:</h2>
    <%= render './venues/list_tiles' %>
<% else %>
    <p class="note">This artist has not booked any shows yet.</p>
<% end %>