config/routes.rb
Rails.application.routes.draw do
  resources :user_venues
  resources :user_artists
  get '/remove_users', to: 'user_artists#remove'
  get '/remove_venues', to: 'user_venues#remove'
  resources :users
  resources :artist_genres
  resources :artist_likes
  resources :genres
  resources :bookings
  resources :posts
  # get '/posts/new/:artist_id', to: 'posts#new', as: 'posts/new'
  # post '/posts/new/:artist_id', to: 'posts#create'
  resources :venues
  resources :artists
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/home', to: 'static#home'
  post '/venues/endorse', to: 'venues#endorse'
  post '/venues/unendorse', to: 'venues#unendorse'
  get '/search', to: 'artists#search'

  post '/artists/like', to: 'artists#like'
  get '/artists/like', to: 'artists#like'
  post '/artists/like_tile', to: 'artists#like_tile'
  post '/artists/unlike', to: 'artists#unlike'

  # get '/artists/posts', to: 'artists#posts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :bookings
    has_many :artist_genres
    has_many :genres, through: :artist_genres
    accepts_nested_attributes_for :genres
    has_many :posts
    has_many :venues, through: :bookings
    has_many :artist_likes
    has_many :venues, through: :artist_likes
    has_one_attached :avatar
    validates :name, presence: true
    has_many :user_artists
    has_many :users, through: :user_artists
    has_many :user_likes_artists
    # has_many :users, through: :user_likes_artists #remains to be seen if this messes with other artist.users
    
    def artist_avatar
        if self.avatar.attached?
            image_tag artist.avatar
        else
            image_tag 'default_avatar.jpg'
        end
    end

    def likers    
        self.user_likes_artists.map {|l| l.user}
    end    
   

end

app/models/artist_genre.rb
class ArtistGenre < ApplicationRecord
    belongs_to :artist 
    belongs_to :genre
end

app/models/artist_like.rb
class ArtistLike < ApplicationRecord
    belongs_to :artist 
    belongs_to :venue
end

app/models/booking.rb
class Booking < ApplicationRecord
    extend SimpleCalendar
    # has_calendar 
    belongs_to :artist
    belongs_to :venue
    validates :title, presence: true
    has_one_attached :show_pic

    def format_time
        "Time: #{self.start_date.strftime("%A, %B %d, %Y at %I:%M %p")} to #{self.end_time.strftime("%I:%M %p")}."
    end



    def datetime_format(datetime)
        datetime.strftime("%A, %B %e, %Y, %I:%M %p")
    end

    def date_format(date)
        date.strftime("%A, %B %e, %Y")
    end

    def time_format(time)
        time.strftime("%l:%M %p")
    end

    def time
        "#{time_format(self.start_date)} - #{time_format(self.end_time)}"
    end

    def date
        self.start_date.to_date
    end

    def artist_name
        self.artist ? self.artist.name : nil
    end

    def artist_name=(name)
        self.artist = Artist.find_by(name: name)
    end
    
    def venue_name
        self.venue ? self.venue.name : nil    
    end

    def venue_name=(name)
        self.venue = Venue.find_by(name: name)
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :artist_genres
    has_many :artists, through: :artist_genres
 
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :artist
    has_one_attached :media

    def content_type
        self.media.blob.content_type
    end

    def video?
        self.content_type.include?("video")
    end

    def image?
        self.content_type.include?("image" || "jpeg")
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, uniqueness: true
    has_many :user_artists
    has_many :artists, through: :user_artists
    has_many :user_venues
    has_many :venues, through: :user_venues
    has_many :posts, through: :artists
    has_many :user_likes_artists
    # has_many :artists, through: :user_likes_artists #it remains to be seen what impact this will have on user.artists as set through admin


    def other_users
        User.all.select do |user|
            user != self
        end
    end

    def artist_admin(artist)
        artist.users.select {|u| u != self}
    end

    def venue_admin(venue)
        venue.users.select {|u| u != self}
    end

    
end

app/models/user_artist.rb
class UserArtist < ApplicationRecord
    belongs_to :user 
    belongs_to :artist


end

app/models/user_likes_artist.rb
class UserLikesArtist < ApplicationRecord
    belongs_to :user
    belongs_to :artist
end

app/models/user_venue.rb
class UserVenue < ApplicationRecord
    belongs_to :user 
    belongs_to :venue
end

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :bookings
    has_many :artists, through: :bookings
    has_many :artist_likes
    has_many :user_venues
    has_many :users, through: :user_venues
    has_one_attached :picture
    accepts_nested_attributes_for :users

    def future_shows
        self.bookings.select {|b| b.start_date > DateTime.now} 
    end

    def next_show

    end

    def past_shows
        self.bookings.select {|b| b.start_date < DateTime.now}
    end

    def nice_description
        if self.description
            self.description.humanize
        end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    # before_action :find_user, only: [:show]
    def new
        @user = User.new
    end

    def create
        #byebug
        @user=User.new(user_params)
        if @user.save
            @user.save
            session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            render :new
        end
    end

    def show #use current_user
        @user = User.find_by(id: params[:id])
        if current_user.nil?
            redirect_to login_path
        end
        if current_user 
            if @user.nil? || @user.id != current_user.id
            @artists = current_user.artists 
            @venues = current_user.venues
            redirect_to user_path(current_user)
            end
        end
        @booking = Booking.new
    end

    def index
        @users = User.all
    end

    private

    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end

    # def find_user
    #     @user = User.find_by(id: params[:id])
    # end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_likes_helper.rb
module ArtistLikesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_artists_helper.rb
module UserArtistsHelper
end

app/helpers/user_venues_helper.rb
module UserVenuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/users/index.html.erb
<h1 class="title">Users</h1>
<%@users.each do |u| %>
    <div class="tile" >
        <div>
            <% u.artists.each do |ua| %>
                <%= link_to ua.name, ua %>
            <% end %>
        </div>
        <%= u.username  %>
    </div>
<% end %>

app/views/users/new.html.erb
<div class="login-header">
<h1>Create a New Account</h1>
<div>
<ul>
<%if @user.errors.any? %>
<%@user.errors.full_messages.each do |msg|%>
<li><%=msg%></li>
<%end%>
<%end%>
</ul>

<div class="container create">
<%=form_for @user do |f|%>
<%=f.label :username%>
<%=f.text_field :username%> <br>
<%=f.label :password%>
<%=f.password_field :password%><br>
<%=f.label :password_confirmation%>
<%=f.password_field :password_confirmation%> <br>
<%=f.submit "Create User"%>
<%end%>
</div>
</div>

app/views/users/show.html.erb
<h1>Welcome, <%=current_user.username%></h1>

<div>

    <h2>My Artists</h2>
    <div class="controls">
    <%=button_to "Create a New Artist Page", new_artist_path, method: 'get'%>
    <% if current_user.artists != [] %>
        <%=button_to "Add Admin for Artists", new_user_artist_path, method: "get"%>
    <% end %>
    </div>
    <% if current_user.artists != [] %>
        <%= render './artists/list_tiles' %>
    <%else%>
        <p>No Artists</p>
    <%end%>
    
</div>



<div>
    <h2>My Venues</h2> 
    <div class="controls">
        <%=button_to "Create a New Venue Page", new_venue_path, method: 'get'%>
        <% if current_user.venues != [] %>
            <%=button_to "Add Admin for Venues", new_user_venue_path, method: "get"%>
        <% end %>
    </div>
    <div>
    <% if current_user.venues != [] || current_user.venues.nil? %>
    <% @venues = current_user.venues %>
        <%= render './venues/list_tiles' %>
    <%else%>
        <p>You have not booked anything yet.</p>
    <%end%>
    </div>
</div>