config/routes.rb
Rails.application.routes.draw do
  resources :user_venues
  resources :user_artists
  get '/remove_users', to: 'user_artists#remove'
  get '/remove_venues', to: 'user_venues#remove'
  resources :users
  resources :artist_genres
  resources :artist_likes
  resources :genres
  resources :bookings
  resources :posts
  # get '/posts/new/:artist_id', to: 'posts#new', as: 'posts/new'
  # post '/posts/new/:artist_id', to: 'posts#create'
  resources :venues
  resources :artists
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/home', to: 'static#home'
  post '/venues/endorse', to: 'venues#endorse'
  post '/venues/unendorse', to: 'venues#unendorse'
  get '/search', to: 'artists#search'

  post '/artists/like', to: 'artists#like'
  get '/artists/like', to: 'artists#like'
  post '/artists/like_tile', to: 'artists#like_tile'
  post '/artists/unlike', to: 'artists#unlike'

  # get '/artists/posts', to: 'artists#posts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :bookings
    has_many :artist_genres
    has_many :genres, through: :artist_genres
    accepts_nested_attributes_for :genres
    has_many :posts
    has_many :venues, through: :bookings
    has_many :artist_likes
    has_many :venues, through: :artist_likes
    has_one_attached :avatar
    validates :name, presence: true
    has_many :user_artists
    has_many :users, through: :user_artists
    has_many :user_likes_artists
    # has_many :users, through: :user_likes_artists #remains to be seen if this messes with other artist.users
    
    def artist_avatar
        if self.avatar.attached?
            image_tag artist.avatar
        else
            image_tag 'default_avatar.jpg'
        end
    end

    def likers    
        self.user_likes_artists.map {|l| l.user}
    end    
   

end

app/models/artist_genre.rb
class ArtistGenre < ApplicationRecord
    belongs_to :artist 
    belongs_to :genre
end

app/models/artist_like.rb
class ArtistLike < ApplicationRecord
    belongs_to :artist 
    belongs_to :venue
end

app/models/booking.rb
class Booking < ApplicationRecord
    extend SimpleCalendar
    # has_calendar 
    belongs_to :artist
    belongs_to :venue
    validates :title, presence: true
    has_one_attached :show_pic

    def format_time
        "Time: #{self.start_date.strftime("%A, %B %d, %Y at %I:%M %p")} to #{self.end_time.strftime("%I:%M %p")}."
    end



    def datetime_format(datetime)
        datetime.strftime("%A, %B %e, %Y, %I:%M %p")
    end

    def date_format(date)
        date.strftime("%A, %B %e, %Y")
    end

    def time_format(time)
        time.strftime("%l:%M %p")
    end

    def time
        "#{time_format(self.start_date)} - #{time_format(self.end_time)}"
    end

    def date
        self.start_date.to_date
    end

    def artist_name
        self.artist ? self.artist.name : nil
    end

    def artist_name=(name)
        self.artist = Artist.find_by(name: name)
    end
    
    def venue_name
        self.venue ? self.venue.name : nil    
    end

    def venue_name=(name)
        self.venue = Venue.find_by(name: name)
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :artist_genres
    has_many :artists, through: :artist_genres
 
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :artist
    has_one_attached :media

    def content_type
        self.media.blob.content_type
    end

    def video?
        self.content_type.include?("video")
    end

    def image?
        self.content_type.include?("image" || "jpeg")
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, uniqueness: true
    has_many :user_artists
    has_many :artists, through: :user_artists
    has_many :user_venues
    has_many :venues, through: :user_venues
    has_many :posts, through: :artists
    has_many :user_likes_artists
    # has_many :artists, through: :user_likes_artists #it remains to be seen what impact this will have on user.artists as set through admin


    def other_users
        User.all.select do |user|
            user != self
        end
    end

    def artist_admin(artist)
        artist.users.select {|u| u != self}
    end

    def venue_admin(venue)
        venue.users.select {|u| u != self}
    end

    
end

app/models/user_artist.rb
class UserArtist < ApplicationRecord
    belongs_to :user 
    belongs_to :artist


end

app/models/user_likes_artist.rb
class UserLikesArtist < ApplicationRecord
    belongs_to :user
    belongs_to :artist
end

app/models/user_venue.rb
class UserVenue < ApplicationRecord
    belongs_to :user 
    belongs_to :venue
end

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :bookings
    has_many :artists, through: :bookings
    has_many :artist_likes
    has_many :user_venues
    has_many :users, through: :user_venues
    has_one_attached :picture
    accepts_nested_attributes_for :users

    def future_shows
        self.bookings.select {|b| b.start_date > DateTime.now} 
    end

    def next_show

    end

    def past_shows
        self.bookings.select {|b| b.start_date < DateTime.now}
    end

    def nice_description
        if self.description
            self.description.humanize
        end
    end

end

app/controllers/venues_controller.rb
class VenuesController < ApplicationController

    before_action :find_venue, only: [:show, :edit, :delete, :update]

    def show
        @bookings = @venue.bookings
        @booking = Booking.new
        @artists = @venue.artists
    end

    def index
        @allvenues = Venue.all
        @venues = @allvenues
        if params[:q] && params[:q].length > 0 
            @venues = @venues.select {|v| v.location.downcase.include?(params[:q].downcase) || 
                v.name.downcase.include?(params[:q].downcase) ||
                v.category.downcase.include?(params[:q].downcase)    } 
        end
    end

    def new
        require_login
        @venue = Venue.new
    end

    def create
        @venue = Venue.new(venue_params)
        if @venue.valid?
            @venue.save
            UserVenue.create(user: current_user, venue: @venue)
            redirect_to venue_path(@venue)
        else
            render 'new'
        end
    end

    def edit
        require_login
    end

    
    def update
        if @venue.valid?
            @venue.update(venue_params)
            redirect_to venue_path(@venue)
        else
            render 'edit'
        end
    end
    
    def endorse
        venue = Venue.find(venue_params[:venue_id])
        artist = Artist.find_by(name: venue_params[:artist_name])
        like = venue.artist_likes.build(artist: artist)
        like.save
        redirect_to venue_path(venue)
    end

    def unendorse
        venue = Venue.find(venue_params[:venue_id])
        artist = Artist.find_by(name: venue_params[:artist_name])
        likes = venue.artist_likes.select { |al| al.artist_id == artist.id }
        likes.each {|l| l.delete }
        redirect_to venue_path(venue)
    end


    private

    def find_venue
        @venue = Venue.find(params[:id])
    end
    
    def venue_params
        params.require(:venue).permit(:name, :location, :category, :capacity, :description, :artist_name, :venue_id, :picture, :username, :user)
    end

    def require_login
        unless session.include? :user_id
        redirect_to login_path
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artist_likes_helper.rb
module ArtistLikesHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_artists_helper.rb
module UserArtistsHelper
end

app/helpers/user_venues_helper.rb
module UserVenuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/venues/_form.html.erb
<%= form_for @venue do |f| %>
   <%= f.label :name %>
   <%= f.text_field :name %><br>
   <%= f.label :location %>
   <%= f.text_field :location %><br>
   <%= f.label :description %>
   <%= f.text_field :description %><br>
   <%= f.label :category %>
   <%= f.text_field :category %><br>
   <%= f.label :capacity %>
   <%= f.number_field :capacity %><br>
   <%= f.file_field :picture%><br>
   <%= f.submit %>
<% end %>


<% if @venue.users.count > 0 %>
   Current Users with admin rights:
   <% @venue.users.each do |user|%>
         <%=user.username%>
   <%end%>
<%end %>
<hr>

<%current_user.venue_admin(@venue).each do |user|%> 
    <%=user.username%>
<%end%>

app/views/venues/_list_tiles.html.erb
<% @venues.each do |venue| %>

        <div class="tile <%= current_user && venue.users.include?(current_user) && ! @artist ? "mine" : "" %> 
            <%= @artist && @artist.venues.include?(venue) ? "endorsed" : "" %>">
            <a href="<%=venue_path(venue)%>">

                <%if venue.picture.attached?%>
                    <%=image_tag venue.picture, class: "headshot" %>
                 <%elsif venue.image_url%>
                     <%= image_tag venue.image_url, class: "headshot" %>
                 <%end%>
                <p ><%= venue.name %></p>
            </a>
                <p><%= venue.location %> </p>
        </div>
<% end %>

app/views/venues/edit.html.erb
<h1> Update this Venue </h1>
<%= render 'form' %> 
<%= %>

app/views/venues/index.html.erb
<h1>Venues</h1>

<div class="search">
  <%= form_tag(venues_path, method: "get") do %>
    <%= label_tag(:q, "Location, Category, or Name:") %>
    <%= text_field_tag(:q, params[:q]) %>
    <%= submit_tag ("Search")%>
  <% end %>

  </div>

<%= render 'list_tiles' %>

app/views/venues/new.html.erb
<h1>Register a Venue  </h1>

<%= render 'form' %>

app/views/venues/show.html.erb
<h1> <%= @venue.name %> </h1>

<h2> <%= @venue.location %></h2> 
<p> Capacity: <%= @venue.capacity %></p>

<p> <%= @venue.nice_description %> </p>

<% if @venue.future_shows.count > 0 %>
    <h2> Upcoming Shows: </h2>
    <%= render './bookings/list_tiles' %>
<% end %>

<% if current_user && current_user.venues.include?(@venue)%>
    <%=form_tag remove_venues_path, method: 'get' do %>
        <%=hidden_field_tag 'venue_id', @venue.id%>
        <%=submit_tag "Delete Admin"%>
    <%end%>
<%end%>



<% if @venue.past_shows.count > 0 %>
    <h2>Past Shows: </h2>
    <div class="bookings">
    <% @bookings.each do |booking|%>
        <div class="tile">
            <% if booking.image_url %> 
                <%=  image_tag booking.image_url, class: 'icon'  %>
            <% end %>
            <p><%=link_to booking.title, booking_path(booking)%></p>
            <p><%=link_to booking.venue.name, venue_path(booking.venue)%>
            <p><%=booking.artist.name%></p>
            <p><%=booking.date_format(booking.start_date)%></p>
            <p><%=booking.time%></p>
            <p><%=booking.description%></p>
        </div>
    <% end %>
    </div>
<% end %>

<% if @venue.artist_likes.count > 0 %>
    <h2>Endorsed Artists: </h2>
    <ul class="thumb_display"> 
        <% @venue.artist_likes.each do |l| %>
            <li>  
                <a href="<%=artist_path(l.artist)%>"><img class="headshot" src="<%=l.artist.image_url%>" />
                <br>
                <%=l.artist.name%></a>
            </li>
        <% end %>
    </ul>
<% end %>

<% if current_user && current_user.venues.include?(@venue) %>
    <div class="booking_form">
    <h3 class="rotate">Book an Artist</h3>
    <%= render './bookings/form' %>
    </div>
<% end %>

<h2> Shows at this Venue </h2>
<%= render './bookings/calendar' %>

<% if @venue.artists.count > 0 %>
<h2>Artists who have played here </h2>
<%= render './artists/list_tiles' %>
<% end %>