config/routes.rb
Rails.application.routes.draw do
  resources :user_venues
  resources :user_artists
  get '/remove_users', to: 'user_artists#remove'
  get '/remove_venues', to: 'user_venues#remove'
  resources :users
  resources :artist_genres
  resources :artist_likes
  resources :genres
  resources :bookings
  resources :posts
  # get '/posts/new/:artist_id', to: 'posts#new', as: 'posts/new'
  # post '/posts/new/:artist_id', to: 'posts#create'
  resources :venues
  resources :artists
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  post '/logout', to: 'sessions#destroy'
  get '/home', to: 'static#home'
  post '/venues/endorse', to: 'venues#endorse'
  post '/venues/unendorse', to: 'venues#unendorse'
  get '/search', to: 'artists#search'

  post '/artists/like', to: 'artists#like'
  get '/artists/like', to: 'artists#like'
  post '/artists/like_tile', to: 'artists#like_tile'
  post '/artists/unlike', to: 'artists#unlike'

  # get '/artists/posts', to: 'artists#posts'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/artist.rb
class Artist < ApplicationRecord
    has_many :bookings
    has_many :artist_genres
    has_many :genres, through: :artist_genres
    accepts_nested_attributes_for :genres
    has_many :posts
    has_many :venues, through: :bookings
    has_many :artist_likes
    has_many :venues, through: :artist_likes
    has_one_attached :avatar
    validates :name, presence: true
    has_many :user_artists
    has_many :users, through: :user_artists
    has_many :user_likes_artists
    # has_many :users, through: :user_likes_artists #remains to be seen if this messes with other artist.users
    
    def artist_avatar
        if self.avatar.attached?
            image_tag artist.avatar
        else
            image_tag 'default_avatar.jpg'
        end
    end

    def likers    
        self.user_likes_artists.map {|l| l.user}
    end    
   

end

app/models/artist_genre.rb
class ArtistGenre < ApplicationRecord
    belongs_to :artist 
    belongs_to :genre
end

app/models/artist_like.rb
class ArtistLike < ApplicationRecord
    belongs_to :artist 
    belongs_to :venue
end

app/models/booking.rb
class Booking < ApplicationRecord
    extend SimpleCalendar
    # has_calendar 
    belongs_to :artist
    belongs_to :venue
    validates :title, presence: true
    has_one_attached :show_pic

    def format_time
        "Time: #{self.start_date.strftime("%A, %B %d, %Y at %I:%M %p")} to #{self.end_time.strftime("%I:%M %p")}."
    end



    def datetime_format(datetime)
        datetime.strftime("%A, %B %e, %Y, %I:%M %p")
    end

    def date_format(date)
        date.strftime("%A, %B %e, %Y")
    end

    def time_format(time)
        time.strftime("%l:%M %p")
    end

    def time
        "#{time_format(self.start_date)} - #{time_format(self.end_time)}"
    end

    def date
        self.start_date.to_date
    end

    def artist_name
        self.artist ? self.artist.name : nil
    end

    def artist_name=(name)
        self.artist = Artist.find_by(name: name)
    end
    
    def venue_name
        self.venue ? self.venue.name : nil    
    end

    def venue_name=(name)
        self.venue = Venue.find_by(name: name)
    end

end

app/models/genre.rb
class Genre < ApplicationRecord
    has_many :artist_genres
    has_many :artists, through: :artist_genres
 
end

app/models/post.rb
class Post < ApplicationRecord
    belongs_to :artist
    has_one_attached :media

    def content_type
        self.media.blob.content_type
    end

    def video?
        self.content_type.include?("video")
    end

    def image?
        self.content_type.include?("image" || "jpeg")
    end
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates :username, uniqueness: true
    has_many :user_artists
    has_many :artists, through: :user_artists
    has_many :user_venues
    has_many :venues, through: :user_venues
    has_many :posts, through: :artists
    has_many :user_likes_artists
    # has_many :artists, through: :user_likes_artists #it remains to be seen what impact this will have on user.artists as set through admin


    def other_users
        User.all.select do |user|
            user != self
        end
    end

    def artist_admin(artist)
        artist.users.select {|u| u != self}
    end

    def venue_admin(venue)
        venue.users.select {|u| u != self}
    end

    
end

app/models/user_artist.rb
class UserArtist < ApplicationRecord
    belongs_to :user 
    belongs_to :artist


end

app/models/user_likes_artist.rb
class UserLikesArtist < ApplicationRecord
    belongs_to :user
    belongs_to :artist
end

app/models/user_venue.rb
class UserVenue < ApplicationRecord
    belongs_to :user 
    belongs_to :venue
end

app/models/venue.rb
class Venue < ApplicationRecord
    has_many :bookings
    has_many :artists, through: :bookings
    has_many :artist_likes
    has_many :user_venues
    has_many :users, through: :user_venues
    has_one_attached :picture
    accepts_nested_attributes_for :users

    def future_shows
        self.bookings.select {|b| b.start_date > DateTime.now} 
    end

    def next_show

    end

    def past_shows
        self.bookings.select {|b| b.start_date < DateTime.now}
    end

    def nice_description
        if self.description
            self.description.humanize
        end
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/artists_helper.rb
module ArtistsHelper
end

app/helpers/bookings_helper.rb
module BookingsHelper
end

app/helpers/genres_helper.rb
module GenresHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/user_venues_helper.rb
module UserVenuesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/venues_helper.rb
module VenuesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <title>BookMe</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  
<nav class="navbar navbar-expand-lg">

  <a class="navbar-brand" href="/artists">Artists</a>  
  <a class="navbar-brand" href="/venues">Venues</a>  
  <a class="navbar-brand" href="/bookings">Calendar</a> 
  <a class="navbar-brand" href="/posts">News</a> 
  <% if current_user && @venue && current_user.venues.include?(@venue) %>
    <%= link_to "Edit this Venue", edit_venue_path(@venue), class: "navbar-brand admin" %>
  <% end %>
  <% if current_user && @venue && current_user.venues.include?(@venue)%>
    <%=form_tag remove_venues_path, method: 'get' do %>
        <%=hidden_field_tag 'venue_id', @venue.id%>
        <%=submit_tag "Delete Admin", class: "navbar-brand admin"%>
    <%end%>
  <%end%>
  <%if current_user && @artist && current_user.artists.include?(@artist)%>
    <%=link_to "Edit Artist", edit_artist_path(@artist), method: 'get', class: "navbar-brand admin" %>
    <%=link_to "Delete Artist", artist_path(@artist), method: 'delete', class: "navbar-brand admin" %>
  <% end %>
  <%if current_user && current_user.artists.include?(@artist)%>

        <%=form_tag remove_users_path, method: 'get' do %>
            <%=hidden_field_tag 'artist_id', @artist.id%>
            <%=submit_tag "Delete Admin", class: "navbar-brand admin"%>
        <%end%>
    <%end%>
  <%if !current_user%>
    <%=link_to "Login", login_path, class: "navbar-brand"%>
  <%end%>
  <%if current_user%>
    <%=link_to "Dashboard", user_path(current_user), class: "navbar-brand"%>
    <%=link_to "Logout", logout_path, method: 'destroy', class: "navbar-brand"%>
  <%end%>

</nav>


  <body>
    <div class="content">
      <%= yield %>
    </div>
  </body>
</html>